// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaBRFdAHBd6p_vkxuAsmMzA3fzN0CH1v0',
    appId: '1:556578463925:web:6c46e94c7bfe8fd4229efc',
    messagingSenderId: '556578463925',
    projectId: 'fasum-app-14368',
    authDomain: 'fasum-app-14368.firebaseapp.com',
    storageBucket: 'fasum-app-14368.appspot.com',
    measurementId: 'G-BN820SFYLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtq6yZx7-y4dS0ktdu6RiFBOFDX_A6kpM',
    appId: '1:556578463925:android:7176b880a7860701229efc',
    messagingSenderId: '556578463925',
    projectId: 'fasum-app-14368',
    storageBucket: 'fasum-app-14368.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3BxxQ3mjMOvCpXjL0rYHIeWbccPxjaPY',
    appId: '1:556578463925:ios:1fd00eaa9a52db95229efc',
    messagingSenderId: '556578463925',
    projectId: 'fasum-app-14368',
    storageBucket: 'fasum-app-14368.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3BxxQ3mjMOvCpXjL0rYHIeWbccPxjaPY',
    appId: '1:556578463925:ios:719795f86d5a8503229efc',
    messagingSenderId: '556578463925',
    projectId: 'fasum-app-14368',
    storageBucket: 'fasum-app-14368.appspot.com',
    iosBundleId: 'com.example.fasum.RunnerTests',
  );
}
